require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

# Rails cops
Rails:
  Enabled: true

# Metrics
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# RSpec cops
RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5
